# Generated by Django 2.2.10 on 2020-08-13 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200813_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pubdate',
            field=models.DateTimeField(null=True, verbose_name='發佈時間'),
        ),
    ]
