# Generated by Django 2.2.10 on 2020-08-14 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200814_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pubdate',
            field=models.DateField(blank=True, null=True, verbose_name='發佈時間'),
        ),
    ]
