# Generated by Django 2.2.10 on 2020-08-14 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200814_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pubdate',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='發佈時間'),
        ),
    ]
