# Generated by Django 2.2.10 on 2020-08-14 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200814_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pubdate',
            field=models.DateTimeField(null=True, verbose_name='發佈時間'),
        ),
    ]
